//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMFItem
    {
        public int DMFItemId { get; set; }
        public string DMFItemName { get; set; }//市场基项目名称
        public string DMFItemNameEn { get; set; }//市场基金项目名称英文
        public string DMFItemRemark { get; set; }//概述
        public Nullable<bool> ExpenseAccountChk { get; set; }//是否报销
        public Nullable<bool> PublishChk { get; set; }//是否发布
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
