//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAccount
    {
        public int ExpenseAccountId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> DMFItemId { get; set; }
        public Nullable<int> MarketActionId { get; set; }
        public string ExpenseAmt { get; set; }
        public string ApplyStatus { get; set; }
        public string ApprovalReason { get; set; }
        public string ReplyStatus { get; set; }
        public string ReplyReason { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
