//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketAction
    {
        public int MarketActionId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ActionName { get; set; }
        public string ActionCode { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public string MarketActionStatusCode { get; set; }
        public string MarketActionTargetModelCode { get; set; }
        public Nullable<decimal> ActivityBudget { get; set; }
        public Nullable<int> ExpectLeadsCount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ActionPlace { get; set; }
        public Nullable<bool> ExpenseAccount { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
