//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketActionAfter7
    {
        public int MarketActionId { get; set; }
        public string HightLights { get; set; }
        public string ImproveArea { get; set; }
        public string CustomerFeedback { get; set; }
        public Nullable<decimal> ActualExpense { get; set; }
        public Nullable<int> AttendenceOwnerCount { get; set; }
        public Nullable<int> AttendencePCCount { get; set; }
        public Nullable<int> LeadOwnerCount { get; set; }
        public Nullable<int> LeadPCCount { get; set; }
        public Nullable<int> TestDriverOwnerCount { get; set; }
        public Nullable<int> TestDriverPCCount { get; set; }
        public Nullable<int> ActualOrderOwnerCount { get; set; }
        public Nullable<int> ActualOrderPCCount { get; set; }
        public string OnLineAd { get; set; }
        public string CarDisplay { get; set; }
        public string Place { get; set; }
        public string RegisterLiveShow { get; set; }
        public string CustomerStaffModel { get; set; }
        public string Others { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
