//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketActionBefore21
    {
        public int MarketActionId { get; set; }
        public string ActivityBackground { get; set; }
        public string ActivityObjective { get; set; }
        public string ActivityDesc { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> TargetParticipationOwnerCount { get; set; }
        public Nullable<int> TargetParticipationPCCount { get; set; }
        public Nullable<int> TargetLeadsOwnerCount { get; set; }
        public Nullable<int> TargetLeadsPCCount { get; set; }
        public Nullable<int> TargetTestDriveOwnerCount { get; set; }
        public Nullable<int> TargetTestDrivePCCount { get; set; }
        public Nullable<int> TargetOrdersOwnerCount { get; set; }
        public Nullable<int> TargetOrdersPCCount { get; set; }
        public string KeyVision { get; set; }
        public string KeyvisionApproval { get; set; }
        public string POSDesign { get; set; }
        public string PlaceIntro { get; set; }
        public string TestDriverRoadMap { get; set; }
        public string Others { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
